[platformio]
src_dir = .
default_envs = initial, update

[env]
platform = https://github.com/SeeedJP/platform-nordicnrf52.git#8f55ff26c0822ffcbff978be1fddfb8c88c57577
platform_packages =
    framework-arduinoadafruitnrf52 @ https://github.com/SeeedJP/Adafruit_nRF52_Arduino.git#514f28ee405952ecc58558b5e0608a2b63d9901a
framework = arduino
board = seeed_wio_bg770a
board_upload.maximum_size = 397312
monitor_speed = 115200
build_flags =
    -DBOARD_VERSION_1_0
    -DCFG_LOGGER=0
    -DWIO_OTA_SECURE
build_src_filter = +<CellularStatusOta.ino*>
lib_archive = no
lib_deps =
    WioOtaAgent=symlink://../..
    seeedjp/WioCellular@0.3.15
    bblanchon/ArduinoJson@7.0.4

[env:initial]
build_flags =
    ${env.build_flags}
    -DAPP_VERSION=1

[env:update]
build_flags =
    ${env.build_flags}
    -DAPP_VERSION=2

; Both environments require a signed manifest and a local public-key header.
